### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by nsheff** [openschemas/openschemas.github.io#2]
the 'join the community' link on the openschemas home page is broken:

https://openschemas.github.io/howtojoin/

**Comment by vsoch** [comment]
Thanks! I just pushed a fix https://github.com/openschemas/openschemas.github.io/commit/f3b7167af31c5afc16cf8df8f8e51e2a40b2abde

**Comment by vsoch** [comment]
Your lab has a lot of cool software! <3 Need help with anything?

**Comment by nsheff** [comment]
I actually just sent you an e-mail to see if there's a way I could integrate some of what I'm working on with your work! One thing that seems like it may be interesting to you is our work on a [standard, computable project representation](https://pepkit.github.io/). I'm not sure if this can integrate with the scientific filesystem in any way? The other thought was the [epigenome switchboard](http://code.databio.org/episb/) and your work on openschemas...

**Comment by vsoch** [comment]
Yes, let's give it a try! I just sent a message back - PEP would be easy to integrate into SCIF, and I could definitely help with the switchboard.

Feel free to close this issue if the site looks okay, and we can pick up over email.
